{---}
{abstract: 'Perl Modules for using Verizon Cloud offerings'}
{author:}
{  - 'Jason Goth <jason@gothtx.com>'}
{build_requires:}
{  Test::More: 0}
{configure_requires:}
{  ExtUtils::MakeMaker: 0}
{dynamic_config: 1}
{generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.130880'}
{license: mit}
{meta-spec:}
{  url: http://module-build.sourceforge.net/META-spec-v1.4.html}
{  version: 1.4}
{name: Verizon-Perl-Tools}
{no_index:}
{  directory:}
{    - t}
{    - inc}
{requires:}
{  Carp: 0}
{  perl: 5.006}
{version: 0.1_01}
